# Generated by Django 3.2 on 2021-05-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210501_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='acror',
            new_name='actor',
        ),
    ]
