# Generated by Django 3.2 on 2021-05-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_actor_movie_acror'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='acror',
            new_name='actor',
        ),
    ]
