# Generated by Django 3.2 on 2021-05-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_rename_acror_movie_actor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга фильма', 'verbose_name_plural': 'Звезды рейтинга фильма'},
        ),
    ]
